Changes to add bulk insert examples
IBM/nzalchemy pull request #6
Opened 2021-04-26 14:25 UTC by shabbir10july

Some references: 
https://docs.sqlalchemy.org/en/13/_modules/examples/performance/bulk_inserts.html
https://docs.sqlalchemy.org/en/14/orm/examples.html#examples-performance

JIRA: To test bulk insert performance

Solution: Write sample example code for simple bulk insert and compared performance with simple insert.

Testing:

10000 rows insert using nzpy:
--------------------------------
insert using bulk method: 
4-5 mins
insert using ORM add :
11-12 mins 
insert using ORM addall():
6-7 mins

10000 rows insert using nzalchemy:
---------------------------------------
insert using bulk method: 
22 mins
insert using ORM add :
25-27 mins 
insert using ORM addall():
23 mins

2021-05-18 03:51 UTC, abhishekjog commented on sampleApplications/sampleSimpleInsert.py
> +#params = urllib.parse.quote_plus("DRIVER=/nzscratch/client/linux64/lib64/libnzodbc.so;SERVER=localhost;PORT=5480;DATABASE=DB1;UID=admin;PWD=password")
remove commented out code from everywhere

2021-05-18 03:52 UTC, abhishekjog requested changes
please remove commented out code in all places.

2021-05-18 05:29 UTC, shabbir10july commented on sampleApplications/sampleSimpleInsert.py
> +#params = urllib.parse.quote_plus("DRIVER=/nzscratch/client/linux64/lib64/libnzodbc.so;SERVER=localhost;PORT=5480;DATABASE=DB1;UID=admin;PWD=password")
Done

2021-05-19 09:02 UTC, abhishekjog approved these changes

2021-05-19 09:03 UTC, merged